"""Registry for standalone and UP-only agents."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Type

from gogagent.agents.adversarial_judge import AdversarialJudgeAgent
from gogagent.agents.answer_normalizer import AnswerNormalizerAgent
from gogagent.agents.base import Agent
from gogagent.agents.challenger import ChallengerAgent
from gogagent.agents.defender import DefenderAgent
from gogagent.agents.format_checker import FormatCheckerAgent
from gogagent.agents.format_verifier import FormatVerifierAgent
from gogagent.agents.judge import JudgeAgent
from gogagent.agents.mmlu_shuffle import MMLUMajorityVoteAgent, ShuffledMMLUSolverAgent
from gogagent.agents.plan_sketch import PlanSketchAgent
from gogagent.agents.solver import SolverAgent
from gogagent.agents.supervisor import SupervisorAgent
from gogagent.agents.task_brief import TaskBriefAgent
from gogagent.agents.task_classifier import TaskClassifierAgent


@dataclass(frozen=True)
class AgentSpec:
    """Serializable metadata for an agent class."""

    type: str
    role: str
    description: str
    standalone: bool


AGENT_CLASSES: dict[str, Type[Agent]] = {
    cls.agent_type: cls
    for cls in (
        SolverAgent,
        TaskBriefAgent,
        PlanSketchAgent,
        AdversarialJudgeAgent,
        SupervisorAgent,
        FormatVerifierAgent,
        ChallengerAgent,
        DefenderAgent,
        JudgeAgent,
        ShuffledMMLUSolverAgent,
        MMLUMajorityVoteAgent,
        FormatCheckerAgent,
        AnswerNormalizerAgent,
        TaskClassifierAgent,
    )
}


def get_agent_class(agent_type: str) -> Type[Agent]:
    """Return an agent class by type name."""

    try:
        return AGENT_CLASSES[agent_type]
    except KeyError as exc:
        raise ValueError(f"unknown agent type: {agent_type}") from exc


def create_agent(agent_type: str, *, name: str | None = None) -> Agent:
    """Instantiate an agent by type name."""

    return get_agent_class(agent_type)(name=name)


def get_agent(agent_type: str, *, name: str | None = None) -> Agent:
    """Alias used by action builders and older call sites."""

    return create_agent(agent_type, name=name)


def agent_from_dict(data: Mapping[str, Any]) -> Agent:
    """Instantiate an agent from a serialized descriptor."""

    agent_type = str(data.get("type", data.get("agent_type", "")))
    if not agent_type:
        raise ValueError("agent descriptor requires a type")
    return create_agent(agent_type, name=data.get("name"))


def is_standalone_agent(agent_type: str) -> bool:
    """Whether an agent can be generated by a standalone ADD action."""

    return bool(get_agent_class(agent_type).standalone)


def list_agent_specs(*, standalone_only: bool = False) -> list[AgentSpec]:
    """List registered agent metadata."""

    specs = [
        AgentSpec(
            type=cls.agent_type,
            role=cls.role,
            description=cls.description,
            standalone=cls.standalone,
        )
        for cls in AGENT_CLASSES.values()
    ]
    if standalone_only:
        specs = [spec for spec in specs if spec.standalone]
    return specs
