"""Bounded graph-construction actions shared by every domain adapter."""

from __future__ import annotations

from enum import Enum


class MacroAction(str, Enum):
    """Typed graph grammar productions exposed to the policy."""

    EXPAND_ATOMIC_TO_GRAPHAGENT = "EXPAND_ATOMIC_TO_GRAPHAGENT"
    ADD_SUBJECT_EXPERT_GRAPH = "ADD_SUBJECT_EXPERT_GRAPH"
    ADD_OPTION_ELIMINATION_GRAPH = "ADD_OPTION_ELIMINATION_GRAPH"
    ADD_SECOND_OPINION_DEBATE_GRAPH = "ADD_SECOND_OPINION_DEBATE_GRAPH"
    ADD_DECOMPOSE_SOLVE_VERIFY_GRAPH = "ADD_DECOMPOSE_SOLVE_VERIFY_GRAPH"
    ADD_ADVERSARIAL_BEST_ANSWER_GRAPH = "ADD_ADVERSARIAL_BEST_ANSWER_GRAPH"
    ADD_ARITHMETIC_UNIT_CHECK_GRAPH = "ADD_ARITHMETIC_UNIT_CHECK_GRAPH"
    ADD_CRITIQUE_REVISE_GRAPH = "ADD_CRITIQUE_REVISE_GRAPH"
    ADD_SPEC_ANALYZE_CODE_GRAPH = "ADD_SPEC_ANALYZE_CODE_GRAPH"
    ADD_TEST_DEBUG_RETEST_GRAPH = "ADD_TEST_DEBUG_RETEST_GRAPH"
    ADD_ALTERNATIVE_IMPLEMENTATION_GRAPH = "ADD_ALTERNATIVE_IMPLEMENTATION_GRAPH"
    DOWNGRADE_GRAPHAGENT_TO_ATOMIC = "DOWNGRADE_GRAPHAGENT_TO_ATOMIC"
    PRUNE_GRAPHAGENT_MODULE = "PRUNE_GRAPHAGENT_MODULE"
    SET_PAYLOAD_MODE = "SET_PAYLOAD_MODE"
    UPGRADE_NODE_MODEL = "UPGRADE_NODE_MODEL"
    DOWNGRADE_NODE_MODEL = "DOWNGRADE_NODE_MODEL"

    # Backward-compatible aliases for older rollouts and scripts.
    ATTACH_ANALYST = "ATTACH_ANALYST"
    ATTACH_CHECKER = "ATTACH_CHECKER"
    ATTACH_REVISER = "ATTACH_REVISER"
    ATTACH_ALTERNATIVE = "ATTACH_ALTERNATIVE"
    STOP = "STOP"
